### ISSUE TITLE
Panics when the daemon has authentication required

### ISSUE THREAD

**Issue by lindoalex577** [duggavo/MoneroBlock#2]
I am running a node with `--restricted-rpc --rpc-login` for reasons, trying to run MoneroBlock with defaults spits out an error below and exits the program. Even adding auth on `-daemon` (`http://user:password@127.0.0.1:18081`) argument pops out the same error

```
Starting MoneroBlock v0.1.1
Server listening at http://127.0.0.1:31312/
panic: raw request: submit request: non-2xx status code: 401

goroutine 6 [running]:
main.GetHeight(...)
        /home/sysadmin/MoneroBlock/daemon_rpc.go:75
main.GetRecentBlocks()
        /home/sysadmin/MoneroBlock/daemon_rpc.go:89 +0x96
main.UpdateCache()
        /home/sysadmin/MoneroBlock/daemon_rpc.go:151 +0x2a
created by main.StartDaemonRpc
        /home/sysadmin/MoneroBlock/daemon_rpc.go:69 +0x1a8
```

**Comment by duggavo** [comment]
Closed in https://github.com/duggavo/MoneroBlock/commit/7c8172d725390d96b71dddd8f4316a3f275c32d5
