### ISSUE TITLE
not starting?

### ISSUE THREAD

**Issue by Gingeropolous** [duggavo/MoneroBlock#4]
So this might be because I'm an idiot, but I'm trying to run the explorer on a small VPS and I'm using the monerod thats located on another server. 

```
user@xxxx:~/MoneroBlock$ ./moneroblock --daemon xxx:18089 --bind xxxx:80

         __          ___  __    __    __        __     __
|\  /|  /  \  |\  | |    |  \  /  \  |  \ |    /  \   /   | /
| \/ | |    | | \ | |___ |__/ |    | |__/ |   |    | |    |/
|    | |    | |  \| |    | \  |    | |  \ |   |    | |    |\
|    |  \__/  |   | |___ |  \  \__/  |__/ |__  \__/   \__ | \

                 The Trustless Block Explorer


Starting MoneroBlock v0.1.2
Server listening at http://xxxx:80/
user@xxxx:~/MoneroBlock$ 

```

As far as I can tell, the process just stops running after it says its listening. I can't access any webserver on the box, and it just exits to command line. 

Perhaps its because I'm using a remote nodes restricted RPC instead of the normal RPC?

**Comment by ghost** [comment]
Same issue here.
It's up and running without any error and It just doesn't work.

**Comment by ghost** [comment]
Fixed by self-building.
I was using the docker image before.

**Comment by Gingeropolous** [comment]
i compiled myself as well.

**Comment by duggavo** [comment]
> Fixed by self-building. I was using the docker image before.

Does the sha256 sum of the binary you compile (with command `go build -ldflags="-s -w" ./`) match the precompiled hash?

**Comment by Gingeropolous** [comment]
it does not. But does go always built reproducible binaries?

**Comment by duggavo** [comment]
> it does not. But does go always built reproducible binaries?

Not sure, probably they change between go versions.

**Comment by duggavo** [comment]
@Gingeropolous  Are you sure there is nothing listening on port 80? I've found that moneroblock exits without any error (like the log above) if it tries to listen on a "busy" port.

**Comment by Gingeropolous** [comment]
yep, that was it!
